import {CardInterface} from "../_interface/card.interface";

export const cards: CardInterface[] = [
  {
    id: 1,
    name: "Exemple 1",
    content: "ex1",
    isObtained: true,
    nbObtained: 1,
    rarity: 0,
    version: 1,
    type: 0,
    cardBack: {id: 1, url: 'card/card-off.png'},
    cardFront: {id: 2, url: 'card/exemple1.png'}
  },
  {
    id: 2,
    name: "Exemple 2",
    content: "ex2",
    isObtained: true,
    nbObtained: 2,
    rarity: 0,
    version: 1,
    type: 0,
    cardBack: {id: 1, url: 'card/card-off.png'},
    cardFront: {id: 3, url: 'card/exemple2.png'}
  },
  {
    id: 3,
    name: "Exemple 2",
    content: "ex2",
    isObtained: false,
    nbObtained: 0,
    rarity: 0,
    version: 1,
    type: 0,
    cardBack: {id: 1, url: 'card/card-off.png'},
    cardFront: {id: 3, url: 'card/exemple2.png'}
  },
  {
    id: 4,
    name: "Exemple 2",
    content: "ex2",
    isObtained: false,
    nbObtained: 0,
    rarity: 0,
    version: 1,
    type: 0,
    cardBack: {id: 1, url: 'card/card-off.png'},
    cardFront: {id: 3, url: 'card/exemple2.png'}
  },
  {
    id: 5,
    name: "Exemple 2",
    content: "ex2",
    isObtained: false,
    nbObtained: 0,
    rarity: 0,
    version: 1,
    type: 0,
    cardBack: {id: 1, url: 'card/card-off.png'},
    cardFront: {id: 3, url: 'card/exemple2.png'}
  },
  {
    id: 6,
    name: "Exemple 2",
    content: "ex2",
    isObtained: false,
    nbObtained: 0,
    rarity: 0,
    version: 1,
    type: 0,
    cardBack: {id: 1, url: 'card/card-off.png'},
    cardFront: {id: 3, url: 'card/exemple2.png'}
  },
  {
    id: 7,
    name: "Exemple 2",
    content: "ex2",
    isObtained: false,
    nbObtained: 0,
    rarity: 0,
    version: 1,
    type: 0,
    cardBack: {id: 1, url: 'card/card-off.png'},
    cardFront: {id: 3, url: 'card/exemple2.png'}
  },
  {
    id: 8,
    name: "Exemple 2",
    content: "ex2",
    isObtained: false,
    nbObtained: 0,
    rarity: 0,
    version: 1,
    type: 0,
    cardBack: {id: 1, url: 'card/card-off.png'},
    cardFront: {id: 3, url: 'card/exemple2.png'}
  },
  {
    id: 9,
    name: "Exemple 2",
    content: "ex2",
    isObtained: false,
    nbObtained: 0,
    rarity: 0,
    version: 1,
    type: 0,
    cardBack: {id: 1, url: 'card/card-off.png'},
    cardFront: {id: 3, url: 'card/exemple2.png'}
  },
  {
    id: 10,
    name: "Exemple 2",
    content: "ex2",
    isObtained: false,
    nbObtained: 0,
    rarity: 0,
    version: 1,
    type: 0,
    cardBack: {id: 1, url: 'card/card-off.png'},
    cardFront: {id: 3, url: 'card/exemple2.png'}
  },
  {
    id: 11,
    name: "Exemple 2",
    content: "ex2",
    isObtained: false,
    nbObtained: 0,
    rarity: 0,
    version: 1,
    type: 0,
    cardBack: {id: 1, url: 'card/card-off.png'},
    cardFront: {id: 3, url: 'card/exemple2.png'}
  },
  {
    id: 12,
    name: "Exemple 2",
    content: "ex2",
    isObtained: false,
    nbObtained: 0,
    rarity: 0,
    version: 1,
    type: 0,
    cardBack: {id: 1, url: 'card/card-off.png'},
    cardFront: {id: 3, url: 'card/exemple2.png'}
  },
  {
    id: 13,
    name: "Exemple 2",
    content: "ex2",
    isObtained: false,
    nbObtained: 0,
    rarity: 0,
    version: 1,
    type: 0,
    cardBack: {id: 1, url: 'card/card-off.png'},
    cardFront: {id: 3, url: 'card/exemple2.png'}
  },
  {
    id: 14,
    name: "Exemple 2",
    content: "ex2",
    isObtained: false,
    nbObtained: 0,
    rarity: 0,
    version: 1,
    type: 0,
    cardBack: {id: 1, url: 'card/card-off.png'},
    cardFront: {id: 3, url: 'card/exemple2.png'}
  },
  {
    id: 15,
    name: "Exemple 2",
    content: "ex2",
    isObtained: false,
    nbObtained: 0,
    rarity: 0,
    version: 1,
    type: 0,
    cardBack: {id: 1, url: 'card/card-off.png'},
    cardFront: {id: 3, url: 'card/exemple2.png'}
  },
  {
    id: 16,
    name: "Exemple 2",
    content: "ex2",
    isObtained: false,
    nbObtained: 0,
    rarity: 0,
    version: 1,
    type: 0,
    cardBack: {id: 1, url: 'card/card-off.png'},
    cardFront: {id: 3, url: 'card/exemple2.png'}
  },
  {
    id: 17,
    name: "Exemple 2",
    content: "ex2",
    isObtained: false,
    nbObtained: 0,
    rarity: 0,
    version: 1,
    type: 0,
    cardBack: {id: 1, url: 'card/card-off.png'},
    cardFront: {id: 3, url: 'card/exemple2.png'}
  },
  {
    id: 18,
    name: "Exemple 2",
    content: "ex2",
    isObtained: false,
    nbObtained: 0,
    rarity: 0,
    version: 1,
    type: 0,
    cardBack: {id: 1, url: 'card/card-off.png'},
    cardFront: {id: 3, url: 'card/exemple2.png'}
  },
  {
    id: 3,
    name: "Exemple 2",
    content: "ex2",
    isObtained: false,
    nbObtained: 0,
    rarity: 0,
    version: 1,
    type: 0,
    cardBack: {id: 1, url: 'card/card-off.png'},
    cardFront: {id: 3, url: 'card/exemple2.png'}
  },
  {
    id: 4,
    name: "Exemple 2",
    content: "ex2",
    isObtained: false,
    nbObtained: 0,
    rarity: 0,
    version: 1,
    type: 0,
    cardBack: {id: 1, url: 'card/card-off.png'},
    cardFront: {id: 3, url: 'card/exemple2.png'}
  },
  {
    id: 5,
    name: "Exemple 2",
    content: "ex2",
    isObtained: false,
    nbObtained: 0,
    rarity: 0,
    version: 1,
    type: 0,
    cardBack: {id: 1, url: 'card/card-off.png'},
    cardFront: {id: 3, url: 'card/exemple2.png'}
  },
  {
    id: 6,
    name: "Exemple 2",
    content: "ex2",
    isObtained: false,
    nbObtained: 0,
    rarity: 0,
    version: 1,
    type: 0,
    cardBack: {id: 1, url: 'card/card-off.png'},
    cardFront: {id: 3, url: 'card/exemple2.png'}
  },
  {
    id: 7,
    name: "Exemple 2",
    content: "ex2",
    isObtained: false,
    nbObtained: 0,
    rarity: 0,
    version: 1,
    type: 0,
    cardBack: {id: 1, url: 'card/card-off.png'},
    cardFront: {id: 3, url: 'card/exemple2.png'}
  },
  {
    id: 8,
    name: "Exemple 2",
    content: "ex2",
    isObtained: false,
    nbObtained: 0,
    rarity: 0,
    version: 1,
    type: 0,
    cardBack: {id: 1, url: 'card/card-off.png'},
    cardFront: {id: 3, url: 'card/exemple2.png'}
  },
  {
    id: 9,
    name: "Exemple 2",
    content: "ex2",
    isObtained: false,
    nbObtained: 0,
    rarity: 0,
    version: 1,
    type: 0,
    cardBack: {id: 1, url: 'card/card-off.png'},
    cardFront: {id: 3, url: 'card/exemple2.png'}
  },
  {
    id: 10,
    name: "Exemple 2",
    content: "ex2",
    isObtained: false,
    nbObtained: 0,
    rarity: 0,
    version: 1,
    type: 0,
    cardBack: {id: 1, url: 'card/card-off.png'},
    cardFront: {id: 3, url: 'card/exemple2.png'}
  },
  {
    id: 11,
    name: "Exemple 2",
    content: "ex2",
    isObtained: false,
    nbObtained: 0,
    rarity: 0,
    version: 1,
    type: 0,
    cardBack: {id: 1, url: 'card/card-off.png'},
    cardFront: {id: 3, url: 'card/exemple2.png'}
  },
  {
    id: 12,
    name: "Exemple 2",
    content: "ex2",
    isObtained: false,
    nbObtained: 0,
    rarity: 0,
    version: 1,
    type: 0,
    cardBack: {id: 1, url: 'card/card-off.png'},
    cardFront: {id: 3, url: 'card/exemple2.png'}
  },
  {
    id: 13,
    name: "Exemple 2",
    content: "ex2",
    isObtained: false,
    nbObtained: 0,
    rarity: 0,
    version: 1,
    type: 0,
    cardBack: {id: 1, url: 'card/card-off.png'},
    cardFront: {id: 3, url: 'card/exemple2.png'}
  },
  {
    id: 14,
    name: "Exemple 2",
    content: "ex2",
    isObtained: false,
    nbObtained: 0,
    rarity: 0,
    version: 1,
    type: 0,
    cardBack: {id: 1, url: 'card/card-off.png'},
    cardFront: {id: 3, url: 'card/exemple2.png'}
  },
  {
    id: 15,
    name: "Exemple 2",
    content: "ex2",
    isObtained: false,
    nbObtained: 0,
    rarity: 0,
    version: 1,
    type: 0,
    cardBack: {id: 1, url: 'card/card-off.png'},
    cardFront: {id: 3, url: 'card/exemple2.png'}
  },
  {
    id: 16,
    name: "Exemple 2",
    content: "ex2",
    isObtained: false,
    nbObtained: 0,
    rarity: 0,
    version: 1,
    type: 0,
    cardBack: {id: 1, url: 'card/card-off.png'},
    cardFront: {id: 3, url: 'card/exemple2.png'}
  },
  {
    id: 17,
    name: "Exemple 2",
    content: "ex2",
    isObtained: false,
    nbObtained: 0,
    rarity: 0,
    version: 1,
    type: 0,
    cardBack: {id: 1, url: 'card/card-off.png'},
    cardFront: {id: 3, url: 'card/exemple2.png'}
  },
  {
    id: 18,
    name: "Exemple 2",
    content: "ex2",
    isObtained: false,
    nbObtained: 0,
    rarity: 0,
    version: 1,
    type: 0,
    cardBack: {id: 1, url: 'card/card-off.png'},
    cardFront: {id: 3, url: 'card/exemple2.png'}
  },
  {
    id: 18,
    name: "Exemple 2",
    content: "ex2",
    isObtained: false,
    nbObtained: 0,
    rarity: 0,
    version: 1,
    type: 0,
    cardBack: {id: 1, url: 'card/card-off.png'},
    cardFront: {id: 3, url: 'card/exemple2.png'}
  },
  {
    id: 18,
    name: "Exemple 2",
    content: "ex2",
    isObtained: false,
    nbObtained: 0,
    rarity: 0,
    version: 1,
    type: 0,
    cardBack: {id: 1, url: 'card/card-off.png'},
    cardFront: {id: 3, url: 'card/exemple2.png'}
  },
]
